### ISSUE TITLE
Segfault in binary search in word.c

### ISSUE THREAD

**Issue by jbarlow83** [eddieantonio/ocreval#22]
I hit a segfault in the binary search in word.c.

The condition that causes the issue is `midpoint >= len`, if the code point being searched is greater than any in `WORD_BREAK_PROPERTY`. I don't believe `midpoint < 0` can occur but added it for completeness.

The following fixes the segfault, although I'm not certain the solution (`return Other`) is correct under the circumstances:

```diff --git a/src/word.c b/src/word.c
index 625ded6..31a7575 100644
--- a/src/word.c
+++ b/src/word.c
@@ -53,6 +53,10 @@ static wb_property search_for_property(code_point, left, right)
     }

     const size_t midpoint = left + (right - left) / 2;
+    const size_t len = sizeof(WORD_BREAK_PROPERTY) / sizeof(wb_range);
+    if (midpoint >= len || midpoint < 0)
+        return Other;
+
     const wb_range *middle = &WORD_BREAK_PROPERTY[midpoint];

     if (code_point < middle->start) {
```

**Comment by eddieantonio** [comment]
Hey, thanks for the issue report! Do you have a short input that will cause this crash?

**Comment by jbarlow83** [comment]
I believe what happened is a pdf to text extraction pulled out some garbage control characters, which in turn caused:
`search_for_property(0x3, 0, sizeof(WORD_BREAK_PROPERTY) / sizeof(wb_range))`

When the failure occurs:
```
left = 0 
right = 0xffffffff 
midpoint = -1
```

so the issue is that the safety check `(right < left)` is an unsigned comparison and `right` can take on the value `-1` which gets treated as its unsigned equivalent.

**Comment by eddieantonio** [comment]
Hey @jbarlow83. Thanks again for the bug report and your proposed fix. I actually found a more elegant fix, and that was to change the type of `left` and `right` from `size_t` – an unsigned integer type – to `int`. This way, `right` doesn't underflow to the unsigned value of 0xffffffff; it just becomes -1, meaning the signed comparison `right < left` catches this case, and lists the value as `Other` (you were right about this part!)

**Comment by jbarlow83** [comment]
Yes, that's a reasonable way right way to do it. (I didn't actually try to find out what was wrong at first, it just assumed it was wandered out of the array and added a boundary check.)
