### ISSUE TITLE
Support for alto?

### ISSUE THREAD

**Issue by jtlz2** [eddieantonio/ocreval#24]
@eddieantonio I am so thankful to have discovered such a brilliant and elegant toolset - thank you so much for the port!

I am currently doing my analysis on alto files which seem to be widely supported. Is there any chance you might be able to adapt ocreval to take alto files? I worry about other converters - super useful as they are - because everyone's opinions on how to do the translation will vary slightly.

I wonder if the extra positional information of the alto file is not something ocreval could anyway capitalize on though - what about the word confidences?

I use pdfalto to go from machine-readable PDFs to alto, then alto-ocr-text to generate ground-truth text. Do you have another / better way?

On the OCR side, we are outputting alto from Tesseract and ABBYY to name but two.

What do you think? How do you approach this problem yourself?

Thanks so much!

**Comment by eddieantonio** [comment]
Hi @jtlz2!

Thanks for the kind words!

There are no plans for alto files; honestly, I am not familiar at all with this format. When I ported this toolset, it was used by my colleague who was in charge of the OCR. They were most comfortable with the plain text format required by this tool. As it stands, implementing a full-featured ALTO reader would be a substantial undertaking, and I don't believe I have enough time to write and maintain it.

Sorry for the unsatisfying answer! :/

**Comment by jtlz2** [comment]
No problem at all - completely understand - unix philosophy - will close :)
