### ISSUE TITLE
Feature request: automate the accuracy evaluation

### ISSUE THREAD

**Issue by DesBw** [eddieantonio/ocreval#30]
- It would be nice if many files can be checked for accuracy at ones. 
One strategy is to use the same file names for the corrected text and the ocr text. The Accuracy checking tool then runs through the folder and compares them. 

Consider a folder of files like follow: 

Page1.txt
Page1.tex
Page2.txt
Page2.tex

The .tex files are the ground truth provided by the user. The txt files are the outputs from the ocr reader (engine). The accuracy can then be check by one command. The tool will take the files pair by pair (using the file names, and extensions) and outputs the report. 

```
accuracy Page1.tex Page1.txt Page1_report.txt
accuracy Page2.tex Page2.txt Page2_report.txt
```

**Comment by Dellu** [comment]
It can even further automated by combing the reports from each pair of files using **accusum** to produce the final report.
